[package]
name = "c8e-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.18", features = ["json"] }
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
tokio-test = "0.4"
